server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/publicities/**,/api/subscriptions/**
        - id: users-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
        - id: location-service
          uri: lb://location-service
          predicates:
            - Path=/api/coordinates/**
