server:
  port: 8092
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    username: admin
    url: jdbc:mysql://database-1.cyniwvro1qvr.us-east-2.rds.amazonaws.com:3306/locationDB
    password: fas#123456789
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comment: false
        format_sql: false
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
# Eureka Client
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/
Feign:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
hystrix:
  dashboard:
    proxy-stream-allow-list: "*"
